# Generated by Django 5.0.3 on 2024-04-05 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_schedule_teacher_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='course_id',
        ),
    ]
