# Generated by Django 5.0.3 on 2024-04-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_course_student_course_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='student',
            new_name='student_id',
        ),
    ]
