# Generated by Django 5.0.3 on 2024-04-05 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_rename_student_attendance_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='schedule',
            new_name='schedule_id',
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.subject'),
        ),
    ]
