# Generated by Django 5.0.3 on 2024-04-05 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_attendance_subject_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='yearlevel_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.yearlevel'),
        ),
    ]
