# Generated by Django 5.0.3 on 2024-04-05 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_attendance_yearlevel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course_id',
            new_name='course',
        ),
    ]
