# Generated by Django 5.0.3 on 2024-04-06 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_rename_course_id_student_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='schedule_id',
            new_name='schedule_FK',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='student_id',
            new_name='student_FK',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='subject_id',
            new_name='subject_FK',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='teacher_id',
            new_name='teacher_FK',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='course_FK',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='yearlevel_id',
        ),
        migrations.AddField(
            model_name='student',
            name='yearlevel_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.yearlevel'),
        ),
    ]
