# Generated by Django 5.0.3 on 2024-04-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_rename_schedule_id_attendance_schedule_fk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='yearlevel_FK',
        ),
        migrations.AddField(
            model_name='student',
            name='yearlevel_FK',
            field=models.ManyToManyField(to='students.yearlevel'),
        ),
    ]
